INSERT INTO products (name, price, category_id,desciption,image)
VALUES
('Suit', '4500', 3, 'Suit', 'suit.jpg'),
('Airforce one shoes','2800',1,'shoes','airforce_one_shoes.jpg'),
('Denim Jacket', '1500',6,'' ,'denim_jacket.jpg'),
('Denim Trouser', '2000',2,'','denim_trouser.jpg'),
('Leather shoes', '1800',1,'','leather_shoes.jpg'),
('Leather Jacket', '3599',6,'','leather_jacket.jpg'),
('J4 Shoes', '3499',1,'','j4_shoes.jpg'),
('Baggy Pants', '799',2,'','baggy_pants.jpg'),
('Cargo pants', '500',2,'','cargo_pants.jpg'),
('Balaclava', '450',5,'','balaclava.jpg'),
('Baleniciaga shoes', '3200',1,'','balenciaga_shoes.jpg'),
('Adidas shoes', '3500',1,'','adidas_shoes.jpg'),
('Tottenham hotspur kit', '1600',4,'','tottenham_hotspur_kit.jpg'),
('Black Tshirt', '600',4,'','black_tshirt.jpg'),
('White Tshirt', '600',4,'','white_tshirt.jpg'),
('blue trouser', '800',2,'','blue_trouser.jpg'),
('White shirt', '500',4,'','white_shirt.jpg'),
('Blue Shirt', '500',4,'','blue_shirt.jpg'),
('Black Hoddie', '800',3,'','black_hoodie.jpg'),
('Blue sweater', '700',3,'','blue_sweater.jpg'),
('Red shirt', '599',4,'','red_shirt.jpg'),
('Black cap', '400',5,'','black_cap.jpg'),
('Heavy hoddie', '1499',3,'','heavy_hoddie.jpg'),
('Hoddie pull over for women', '1699',3,'','hoddie_pull_over_for_women.jpg'),
('Hoddie sweat shirt', '999',3,'','hoddie_sweat_shirt.jpg'),
('Quality unisex hoddie', '1500',3,'','quality_unisex_hoddie.jpg'),
('Unisex hoddie sweater', '2000',3,'','unisex_hoddie_sweater.jpg'),
('Men zip up hoddie', '1500',3,'','men_zip_up_hoddie.jpg'),
('Women nitted hoddie', '1899',3,'','women_nitted_hoddie.jpg'),
('Women sweater', '1200', 3,'','women_sweater.jpg'),
('Wool sweater', '2499',3,'','wool_sweaters.jpg'),
('Professional security Sweater ', '799',3,'','professional_security_sweaters.jpg'),
('Men Oxford Shirt', '699',4,'','men_oxford_shirt.jpg'),
('Kenya shield Tshirt', '499',4,'','kenya_shield_tshirt.jpg'),
('Oversized Tshirt for men', '700',4,'','oversized_tshirt_for_men.jpg'),
('Short sleeved shirt for Men', '899',4,'','mens_shirt_short_sleeved.jpg'),
('Polo Shirt', '699',4,'','polo_tshirt.jpg'),
('Round-Neck plain tshirt', '599',4,'','round_neck_plain_tshirt.jpg'),
('Stripped shirt for Men', '799',4,'','striped_shirt_for_men.jpg'),
('Custom  cut Tshirt', '600',4,'','custom_cut_tshirt.jpg'),
('Corporate Shirt', '899',4,'','corporate_shirt.jpg'),
('Blue & Grey checked shirt', '700',4,'','blue_grey_check_shirt.jpg'),
('Lucia Stitched Denim baggy jeans', '1299',2,'','lucia_stitched_denim_baggy_jeans.jpg'),
('Oversized Pants baggy jeans', '1500',2,'','oversized_pants_baggy_jeans.jpg'),
('Slim fit black jeans for men', '899',2,'','slim_fit_black_jeans_for_men.jpg'),
('Stretch jeans', '999',2,'','stretch_jeans.jpg'),
('Tapered fit jeans', '1099',2,'','tapered_fit_jeans.jpg'),
('Long loose jeans', '1499',2,'','long_loose_jeans.jpg'),
('High waisted wide leg for women', '1500',2,'','high_waisted_wide_leg_for_women.jpg'),
('High waisted barrel jeans', '1500',2,'','high_waisted_barrel_jeans.jpg'),
('Donna Jeans Stream Sky Retro', '1399',2,'','donna_jeans_stream_sky_retro.jpg'),
('Classic jeans regular light blue', '1200',2,'','classic_jeans_regular_light_blue.jpg'),
('Generic boys casual shoes', '1999',1,'','generic_boys_casual_shoes.jpg'),
('High milage running shoes', '1499',1,'','high_mileage_running_shoes.jpg'),
('Custom sneakers', '3500',1,'','custom_sneakers-shoes.jpg'),
('Chunky shoes', '2500',1,'','chunky_shoes.jpg'),
('Beginner basketball shoes', '2000',1,'','beginner_basketball_shoes.jpg'),
('Ladies sports shoes', '2000',1,'','ladies_sports_shoes.jpg'),
('Men sport sneakers', '2500',1,'','men_sneakers-sport_shoes.jpg'),
('Airforce one custom shoes', '3499',1,'','airforce_one_custom_shoes.jpg'),
('Adidas shoes', '3000',1,'','adidas_shoes.jpg'),
('Leather shoes', '2000',1,'','leather_shoes.jpg'),
('Uflex Cap', '350',5,'','uflex_cap-headwear.jpg'),
('Custom hat', '400',5,'','custom_hat-headwear.jpg'),
('Golf hat', '400',5,'','golf_hat-headwear.jpg'),
('Autumn headwear', '500',5,'','autumn_headwear.jpg'),
('Mammoth headwear', '650',5,'','mammoth_headwear.jpg'),
('Winter headwear', '400',5,'','winter_headwear.jpg'),
('Kenya flag embroided bucket hat', '350',5,'','kenya_flag_embroided_bucket_hat_headwear.jpg'),
('Ceremonial top hat', '799',5,'','ceremonial_top_hat-headwear.jpg'),
('Odyssey headwear', '699',5,'','odyssey_headwear.jpg'),
('Designer headwear', '799',5,'','designer_headwear.jpg'),
('Engine leather jacket', '2500',6,'','engine_leather_jacket_outwear.jpg'),
('Women winter jacket', '3000',6,'','women_winter_jacket_outwear.jpg'),
('Millitary jacket', '3500',6,'','millitary_jacket_outwear'),
('Mens winter knitted outwear', '1500',6,'','mens_winter_knitted_outwear.jpg'),
('Lymio jacket', '2000',6,'','lymio_jacket_outwear.jpg'),
('Kids jacket', '1299',6,'','kids_jacket_outwear.jpg'),
('Denim outwear', '2499',6,'','denim_outwear.jpg'),
('Athletic outwear', '2000',6,'','athletic_outwear.jpg'),
('David outwear jacket', '3499',6,'','david_outwear_jacket.jpg'),
('Twill jacket', '2000',6,'','twill_jacket_outwear.jpg'),







  